apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    dateTime: {}
  artifacts:
  - image: skaffold-gitlab-auto-devops

deploy:
  helm:
    releases:
    - name: skaffold-gitlab-auto-devops
      chartPath: ./chart
      skipBuildDependencies: true
      values:
        auto-deploy-app.image.repository: skaffold-gitlab-auto-devops
      setValues:
        auto-deploy-app.image.tag: ""
