apiVersion: skaffold/v2beta17
kind: Config
build:
  artifacts:
  - image: skaffold-absolute
    context: .
    sync:
      manual:
        - src: '/home/test/**'
          dest: /config/
deploy:
  kubectl:
    manifests:
      - k8s-*
