apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: skaffold-example
test:
  - image: skaffold-example
    custom:
      - command: ./command/test.sh #go run example.go 5 10
        timeout: 60 #in seconds
        dependencies:
          paths:
          - "./command/*_test.go"
deploy:
  kubectl:
    manifests:
      - k8s-*