apiVersion: skaffold/v1alpha4
kind: Config
build:
    artifacts:
    - image: gcr.io/k8s-skaffold/docs-controller
      docker:
        dockerfile: deploy/webhook/Dockerfile
deploy:
  kubectl:
    manifests:
      - deploy/webhook/deployment.yaml
