apiVersion: skaffold/v2beta9
kind: Config
build:
  googleCloudBuild:
    projectId: k8s-skaffold
  artifacts:
  - image: skaffold-example
    kaniko:
      cache: {}
deploy:
  steps:
  - kubectl:
      manifests:
        - k8s-*
