dist: xenial

language: go
go: "1.12.x"
go_import_path: /skaffold

git:
  submodules: false

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      name: "cloud code samples"
      script:
        - make install
        - skaffold config set --kube-context '' local-cluster true
        - ./hack/cloud-code-samples.sh
