dist: xenial

language: go
go: "1.13.x"
go_import_path: /skaffold

git:
  submodules: false

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      name: "integration"
      language: minimal
      before_install:
        - curl -Lo ${HOME}/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.1/kind-linux-amd64
        - chmod +x ${HOME}/bin/kind
      script:
        - make -j integration-in-kind
