dist: xenial

language: go
go: "1.13.x"
go_import_path: /skaffold

git:
  submodules: false

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      name: "checks"
      env:
        - STATICCHECK_CACHE=$HOME/linting
      script:
        - make checks
      cache:
        directories:
          - $STATICCHECK_CACHE
          - $HOME/.cache/go-build
    - os: linux
      name: "Linux unit"
      script:
        - make coverage
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: osx
      name: "OSX unit"
      before_install:
        - curl -Lo ${HOME}/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5rc2/jq-osx-x86_64
        - chmod +x ${HOME}/bin/jq
      script:
        - make quicktest
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: windows
      name: "Windows unit"
      env:
        - GO111MODULE=on
        - GOFLAGS="-mod=vendor"
      script:
        - go test -short -timeout 60s ./...
      cache:
        directories:
          - C:\\Users\\travis\\AppData\\Local\\go-build
    - os: linux
      name: "integration"
      language: minimal
      script:
        - make integration-in-kind
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/.gradle
    - os: linux
      name: "integration minikube"
      language: go
      go: "1.13.x"
      install:
        - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/local/bin/minikube
        - make minikube-cluster
        - | 
          sudo apt-get update && \
          sudo apt-get install --no-install-recommends --no-install-suggests -y \
          jq \
          git \
          unzip \
          python \
          lsb-release \
          openjdk-8-jdk \
          build-essential \
          python-setuptools \
          apt-transport-https \
          software-properties-common \
        - wget -O bazel "https://github.com/bazelbuild/bazel/releases/download/2.0.0/bazel-2.0.0-linux-x86_64" && sudo install bazel /usr/local/bin/
        - wget -O kubectl "https://storage.googleapis.com/kubernetes-release/release/v1.14.10/bin/linux/amd64/kubectl" && sudo install kubectl /usr/local/bin/
        - wget -O gcloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-276.0.0-linux-x86_64.tar.gz && tar -zxf gcloud.tar.gz && sudo cp -r google-cloud-sdk/ /google-cloud-sdk/
        - docker ps
        - KUBECONFIG=/tmp/kubeconfig kubectl get pods -A
      script:
        - make integration-in-minikube
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/.gradle
