dist: xenial
os: linux
language: minimal

git:
  submodules: false

branches:
  only:
    - master

script:
  # - service --status-all
  - |
    sudo echo '{"registry-mirrors": ["https://mirror.gcr.io"], "mtu": 1460, "experimental": true}' > /etc/docker/daemon.json
