dist: xenial

language: go

git:
  submodules: false

go_import_path: github.com/GoogleContainerTools/skaffold

jobs:
  include:
    - os: linux
      go: "1.12.x"
      before_install:
        - curl -Lo ${HOME}/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.4.0/kind-linux-amd64
        - chmod +x ${HOME}/bin/kind
      script: make integration-in-kind
