dist: xenial

language: go
go: "1.12.x"
go_import_path: /skaffold

git:
  submodules: false

branches:
  only:
    - master

os: linux
script:
  - docker info
  - service --status-all
  - ls -R /var/lib/docker
