dist: xenial
os: linux

git:
  submodules: false

language: go
go: "1.12.x"
go_import_path: github.com/GoogleContainerTools/skaffold

env:
- TEST_RUN=0
- TEST_RUN=1
- TEST_RUN=2
- TEST_RUN=3
- TEST_RUN=4
- TEST_RUN=5
- TEST_RUN=6
- TEST_RUN=7
- TEST_RUN=8
- TEST_RUN=9
- TEST_RUN=10
- TEST_RUN=11
- TEST_RUN=12
- TEST_RUN=13
- TEST_RUN=14
- TEST_RUN=15
- TEST_RUN=16
- TEST_RUN=17
- TEST_RUN=18
- TEST_RUN=19

script: make test
