dist: xenial

language: go
go: "1.12.x"
go_import_path: /skaffold

git:
  submodules: false

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      name: "Linux unit"
      env:
        - GOCACHE=$HOME/go-cache
      cache:
        directories:
          - $GOCACHE
      script:
        - make coverage
    - os: osx
      name: "OSX unit"
      env:
        - GOCACHE=$HOME/go-cache
      cache:
        directories:
          - $GOCACHE
      script:
        - make quicktest
    - os: windows
      name: "Windows unit"
      env:
        - GO111MODULE=on
        - GOFLAGS="-mod=vendor"
      script:
        # - go build -o out/skaffold.exe cmd/skaffold/skaffold.go
        - go test -short -timeout 60s ./...
