language: go
os:
  - linux
  - osx

matrix:
  include:
  - go: "1.10.x"
    env: GOLINT_VERSION=v1.9.3
  - go: "1.11.x"
    env: GOLINT_VERSION=v1.10.2

go_import_path: github.com/GoogleContainerTools/skaffold

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - make out/skaffold test
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
