language: go

git:
  submodules: false

os:
  - linux
  - osx
  - windows

go:
  - "1.11.x"
  - "1.12.x"

go_import_path: github.com/GoogleContainerTools/skaffold

script:
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - go: "1.12.x"
      script:
        - make
      after_success: []
    - os: windows
      script:
        - go build -o out/skaffold.exe cmd/skaffold/skaffold.go
        - go test -short -timeout 60s ./...
      after_success: []
