[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  revision = "e8c6a4993fa7c12b6ca56007739116b27ecb84c1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/docker/distribution"
  revision = "v2.7.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.9"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.9"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.9"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "bca49d5b51a50dc5bb17bbf6204c711c6dbded06"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.17.0"

[[constraint]]
  name = "google.golang.org/api"
  revision = "ff7b961889714494dc1feb2e8359298cbd20e5e3"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  revision = "v4.11.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "18.2.0"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  revision = "17861e192dc11fd2f5081df1932c94cce262fa1e"

[[override]]
  name = "github.com/docker/docker"
  revision = "3998dffb806f3887f804b813069f59bc14a7f3c1"

[[constraint]]
  name = "github.com/bmatcuk/doublestar"
  revision = "v1.1.1"

[[constraint]]
  name = "github.com/rjeczalik/notify"
  version = "0.9.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "4d63.com/tz"


[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"
