[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "162ba6016def672690ee4a1f3978368853a1e149"

[[constraint]]
  name = "github.com/docker/cli"
  revision = "4cb3c70f36baeade76879694a587358be2a74854"

[[override]]
 name = "github.com/docker/go-metrics"
 revision = "d466d4f6fd960e01820085bd7e1a24426ee7ef18"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "0c8571ac0ce161a5feb57375a9cdf148c98c0f70"

[[constraint]]
  name = "github.com/moby/buildkit"
  revision = "43e758232a0ac7d50c6a11413186e16684fc1e4f"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v10.6.2"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.17.0"

[[constraint]]
  name = "google.golang.org/api"
  revision = "ff7b961889714494dc1feb2e8359298cbd20e5e3"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  revision = "v4.4.0"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  revision = "dc0a77702ddab8c3dc5630eca7c026d571c1c9b7"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"
