apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-example
      kaniko:
        buildContext:
          localDir: {}
        cache: {}
  cluster:
    pullSecretName: e2esecret
    namespace: default
deploy:
  kubectl:
    manifests:
      - k8s-*
