apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/node-example
    context: backend
    sync:
    - from: '*.js'
      to: .
      flatten: true
deploy:
  kubectl:
    manifests:
    - "backend/k8s/**"
