<<<<<<< HEAD
apiVersion: skaffold/v2beta5
=======
apiVersion: skaffold/v2beta4
>>>>>>> d43417a8588f9c52cf717199deb05ae72757d941
kind: Config
build:
  artifacts:
  - image: react-reload
    context: app
    sync:
      manual:
      - src: 'src/components/*'
        dest: .
      - src: 'src/styles/*'
        dest: .
