apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
  - image: hooks-example
    hooks:
      before:
        - command: ["sh", "-c", "echo pre-build host hook running on $(hostname)!"]
          os: [darwin, linux]
      after:
        - command: ["sh", "-c", "echo post-build host hook running on $(hostname)!"]
          os: [darwin, linux]
    sync: 
      auto: true
      hooks:
        before:
          - host:
              command: ["sh", "-c", "echo pre-sync host hook running on $(hostname)!"]
              os: [darwin]
          - container:
              command: ["sh", "-c", "echo pre-sync container hook running on $(hostname)!"]
        after:
          - host:
              command: ["sh", "-c", "echo post-sync host hook running on $(hostname)!"]
          - container:
              command: ["sh", "-c", "echo post-sync container hook running on $(hostname)!"]
deploy:
  kubectl:
    manifests:
      - k8s-pod.yaml
    hooks:
      before:
        - host:
            command: ["sh", "-c", "echo pre-deploy host hook running on $(hostname)!"]
            os: [darwin]
        - container:
            # this will only run when there's a matching container from a previous deploy iteration like in `skaffold dev` 
            command: ["sh", "-c", "echo pre-deploy container hook running on $(hostname)!"]
            containerName: hooks-example
            podName: hooks-example-pod
      after:
        - host:
            command: ["sh", "-c", "echo post-deploy host hook running on $(hostname)!"]
        - container:
            command: ["sh", "-c", "echo post-deploy container hook running on $(hostname)!"]
            containerName: hooks-example
            podName: hooks-example-pod
profiles:
  - name: deployment
    deploy:
      kubectl:
        manifests:
          - k8s-deployment.yaml
        hooks:
          before:
            - host:
                command: ["sh", "-c", "echo pre-deploy host hook running on $(hostname)!"]
                os: [darwin]
            - container:
                # this will only run when there's a matching container from a previous deploy iteration like in `skaffold dev` 
                command: ["sh", "-c", "echo pre-deploy container hook running on $(hostname)!"]
                containerName: hooks-example*
                podName: hooks-example-deployment*
          after:
            - host:
                command: ["sh", "-c", "echo post-deploy host hook running on $(hostname)!"]
            - container:
                command: ["sh", "-c", "echo post-deploy container hook running on $(hostname)!"]
                containerName: hooks-example* # use a glob pattern to prefix-match the container name for deployments, stateful-sets, etc.
                podName: hooks-example-deployment* # can use a glob pattern to prefix-match the pod name for deployments, stateful-sets, etc.