apiVersion: skaffold/v2beta20
kind: Config
build:
  artifacts:
  - image: hooks-example
    hooks:
      before:
        - command: ["sh", "-c", "./hook.sh"]
          os: [darwin, linux]
        - command: ["cmd.exe", "/C", "hook.bat"]
          os: [windows]
      after:
        - command: ["sh", "-c", "docker images $SKAFFOLD_IMAGE --digests"]
          os: [darwin, linux]
        - command: ["cmd.exe", "/C", "docker images %SKAFFOLD_IMAGE% --digests"]
          os: [windows]
    sync: 
      manual:
        - src: 'hello.txt'
          dest: .
      hooks:
        before:
          - host:
              command: ["sh", "-c", "echo file changes detected: $SKAFFOLD_FILES_ADDED_OR_MODIFIED"]
              os: [darwin, linux]
          - host:
              command: ["cmd.exe", "/C", "echo file changes detected: %SKAFFOLD_FILES_ADDED_OR_MODIFIED%"]
              os: [windows]
          - container:
              command: ["sh", "-c", "echo pre-sync container hook running on $(hostname)!"]
        after:
          - container:
              command: ["sh", "-c", "echo post-sync container hook running on $(hostname)!"]
deploy:
  kubectl:
    manifests:
      - k8s-pod.yaml
