apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: skaffold-example
    runtimes: [go, musl]
test:
  - image: skaffold-example
    structureTests:
      - ./test/*
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: test
    test:
      - image: skaffold-example
        structureTests:
          - ./test/profile_structure_test.yaml
