apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: skaffold-example
      kaniko:
        buildContext:
          localDir: {}
        cache: {}
  cluster:
    pullSecretName: e2esecret
    namespace: default
deploy:
  kubectl:
    manifests:
      - k8s-*
