# using default substitutions, provided by Google Cloud Build
# see: https://cloud.google.com/container-builder/docs/configuring-builds/substitute-variable-values#using_default_substitutions
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/metrics-server:latest'
    - '-f'
    - 'deploy/metrics-server/Dockerfile'
    - '.'

images:
- 'gcr.io/$PROJECT_ID/metrics-server:latest'
