apiVersion: skaffold/v2beta11
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: leeroy-web
      context: leeroy-web
      requires:
        - image: base
          alias: BASE
    - image: leeroy-app
      context: leeroy-app
      requires:
        - image: base
          alias: BASE
    - image: base
      context: base
deploy:
  docker:
    useCompose: false
    images: [leeroy-web, leeroy-app]
portForward:
  - resourceType: Container
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
  - resourceType: Container
    resourceName: leeroy-app
    port: 50051
    localPort: 9001
