<<<<<<< HEAD
apiVersion: skaffold/v2beta5
=======
apiVersion: skaffold/v2beta4
>>>>>>> d43417a8588f9c52cf717199deb05ae72757d941
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      artifactOverrides:
        image: skaffold-helm
