apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
  - image: skaffold-helm
deploy:
  steps:
  - helm:
      releases:
      - name: skaffold-helm
        chartPath: charts
        artifactOverrides:
          image: skaffold-helm
