apiVersion: skaffold/v1beta4
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-please/image
    context: .
    please:
      target: //example:image 
deploy:
  kubectl:
    manifests:
    - example/k8s-pod.yaml
