apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpack:
      builder: "gcr.io/buildpacks/builder"
      env:
      - GOPROXY={{.GOPROXY}}
    sync:
      auto: {}
deploy:
  kubectl: {}
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
