<<<<<<< HEAD
apiVersion: skaffold/v2beta5
=======
apiVersion: skaffold/v2beta4
>>>>>>> d43417a8588f9c52cf717199deb05ae72757d941
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks-node
    buildpack:
      builder: "gcr.io/buildpacks/builder"
    sync:
      auto: {}
