<<<<<<< HEAD
apiVersion: skaffold/v2beta5
=======
apiVersion: skaffold/v2beta4
>>>>>>> d43417a8588f9c52cf717199deb05ae72757d941
kind: Config
build:
  # only build and deploy "base-service" on main profile
  artifacts:
  - image: skaffold-base
    context: base-service
deploy:
  kubectl:
    manifests:
      - 'base-service/*.yaml'

profiles:
  - name: hello
    patches:
      - op: add
        path: /build/artifacts/1
        value:
          image: skaffold-hello
          context: hello-service
      - op: add
        path: /deploy/kubectl/manifests/1
        value: 'hello-service/*.yaml'

  - name: world
    patches:
      - op: add
        path: /build/artifacts/1
        value:
          image: skaffold-world
          context: world-service
      - op: add
        path: /deploy/kubectl/manifests/1
        value: 'world-service/*.yaml'
