apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/image
      custom:
        buildCommand: build.sh
        dependencies:
          paths:
            - .
deploy:
  kubectl:
    manifests:
      - ./k8s/**
