apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: custom-test-example
test:
  - image: custom-test-example
    custom:
      - command: ./test.sh
        timeoutSeconds: 60
        dependencies:
          paths:
          -  "*_test.go"
      - command: echo Hello world!!
        timeoutSeconds: 60
        dependencies:
          paths:
          -  "./test.sh"
          -  "*_test.go"
deploy:
  kubectl:
    manifests:
      - k8s-*