apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: skaffold-example
test:
  - image: skaffold-example
    custom:
      - command: ./test.sh
        timeout: 60 #in seconds
        dependencies:
          paths:
          -  "*_test.go"
deploy:
  kubectl:
    manifests:
      - k8s-*