apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/node-example
    context: backend
    docker:
      buildArgs:
        SCRIPT: "{{.SCRIPT}}"
    sync:
      # Sync all the javascript files that are in the src folder 
      # with the container src folder
      'src/***/*.js': src/
deploy:
  kubectl:
    manifests:
    - "backend/k8s/**"
