apiVersion: v1
kind: ConfigMap
metadata:
  # Validates the yaml schema.
  name: YamlValidate
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/kubeval
        network: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  # Validates that all containers have cpu and memory reservations set.
  name: CPUAndMemory
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kustomize-functions/example-validator-kubeval:v0.1.0
        network: true
