apiVersion: v1
kind: ConfigMap
metadata:
  # Validates the yaml schema.
  name: YamlValidate
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/kpt-functions/kubeval
        network:
          required: true
    config.kubernetes.io/local-config: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kpt-functions/annotate-config
data:
  "annotation_name": "owner"
  "annotation_value": "YOUR-NAME"
