apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/pipeline-example
deploy:
  kubectl:
    manifests:
    - k8s-*
profiles:
- name: oncluster
  build:
    artifacts:
    - image: gcr.io/k8s-skaffold/pipeline-example-pipeline
      context: .
      kaniko:
        buildContext:
          gcsBucket: skaffold-kaniko
    tagPolicy:
      gitCommit: {}
    cluster:
      pullSecretName: kaniko-secret