apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
    - image: leeroy-app
      context: leeroy-app
deploy:
  steps:
    - kubectl:
        manifests:
        - leeroy-app/kubernetes/*
    - kubectl:
        manifests:
        - leeroy-web/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
