apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
      requires:
        - image: base
          alias: BASE
deploy:
  kubectl:
    manifests:
      - leeroy-web/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000

---

apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: leeroy-app
    context: leeroy-app
    requires:
    - image: base
      alias: BASE
deploy:
  kubectl:
    manifests:
    - leeroy-app/kubernetes/*
portForward:
- resourceType: deployment
  resourceName: leeroy-app
  port: http
  localPort: 9001

---

apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: base
    context: base