<<<<<<< HEAD
apiVersion: skaffold/v2beta5
=======
apiVersion: skaffold/v2beta4
>>>>>>> d43417a8588f9c52cf717199deb05ae72757d941
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: ./leeroy-web/
    - image: leeroy-app
      context: ./leeroy-app/
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
