apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
    - image: leeroy-web
      runtimes: [go, musl]
      context: ./leeroy-web/
    - image: leeroy-app
      runtimes: [go, musl]
      context: ./leeroy-app/
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
