apiVersion: skaffold/v1beta1
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: gcr.io/k8s-skaffold/test-file-sync
    context: .
    sync:
      '**/foo*' : .
deploy:
 kubectl:
   manifests:
   - pod.yaml
