apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: skaffold-docs-1234
  name: skaffold-docs-1234
spec:
  ports:
  - port: 1313
    protocol: TCP
    targetPort: 1313
  selector:
    run: skaffold-docs-1234
  type: LoadBalancer
status:
  loadBalancer: {}
