apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: skaffold-docs-1235
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/k8s-skaffold/skaffold-docs
            env:
              - name: BASE_URL
                value: http://skaffold-docs-1235.default.35.226.45.201.nip.io/
