apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: getting-started-kustomize
build:
  artifacts:
  - image: skaffold-kustomize
    context: app
deploy:
  steps:
  - kustomize:
      paths:
      - overlays/dev
profiles:
- name: prod
  deploy:
    steps:
    - kustomize:
        paths:
        - overlays/prod
- name: staging
  deploy:
    steps:
    - kustomize:
        paths:
        - overlays/staging
