<<<<<<< HEAD
apiVersion: skaffold/v2beta5
=======
apiVersion: skaffold/v2beta4
>>>>>>> d43417a8588f9c52cf717199deb05ae72757d941
kind: Config
metadata:
  name: getting-started-kustomize
build:
  artifacts:
  - image: hello-world
deploy:
  kustomize: {}
