apiVersion: skaffold/v2alpha1
kind: Config
build:
  # only build and deploy "base-service" on main profile
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-base
    context: base-service
deploy:
  kubectl:
    manifests:
      - 'base-service/*.yaml'

profiles:
  - name: hello
    patches:
      - op: add
        path: /build/artifacts/1
        value:
          image: gcr.io/k8s-skaffold/skaffold-hello
          context: hello-service
      - op: add
        path: /deploy/kubectl/manifests/1
        value: 'hello-service/*.yaml'
        
  - name: world
    patches:
      - op: add
        path: /build/artifacts/1
        value:
          image: gcr.io/k8s-skaffold/skaffold-world
          context: world-service
      - op: add
        path: /deploy/kubectl/manifests/1
        value: 'world-service/*.yaml'
