apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpack:
      builder: "gcr.io/buildpacks/builder"
      env:
      - GOVERSION=1.13.1
      - GOPROXY={{.GOPROXY}}
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
