apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
  kaniko:
    buildContext: 
      gcsBucket: skaffold-kaniko
    pullSecretName: e2esecret
    namespace: default
    cache: {}
deploy:
  kubectl:
    manifests:
      - k8s-*
