apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
    - image: skaffold-example
      kaniko:
        cache: {}
  cluster:
    pullSecretName: e2esecret
    namespace: default
# If kaniko pod should be run on the tainted node, You can setup tolerations here.
#    tolerations:
#      - key: app
#        operator: "Equal"
#        value: skaffold
#        effect: "NoSchedule"
deploy:
  kubectl:
    manifests:
      - k8s-*
