name: release (linux)

on: [push, pull_request]

jobs:

  build:
    name: Release binary integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kustomize_version: [3.5.4]
        ko_version: [0.4.0]
        kompose_version: [1.21.0]
        container_structure_tests_version: [1.8.0]
        minikube_version: [1.20.0]
        integration_test_partitions: [0, 1, 2, 3]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Make and Install Skaffold binary from current PR
      run: |
        make
        sudo install "/home/$(whoami)/work/skaffold/skaffold/out/skaffold" /usr/local/bin/skaffold
      
    - name: Run integration tests
      env:
        TOKEN: ${{ secrets.TOKEN }}
        INTEGRATION_TEST_ARGS: "-v"
      run: |
        skaffold config set --global collect-metrics false
        sudo IT_PARTITION=${{ matrix.integration_test_partitions }} make integration-in-minikube
