name: PR (windows)

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:

  build:
    name: PR integration tests
    runs-on: windows-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run integration tests
      run: |
         go test -short -timeout 60s ./...
