name: per-pr (darwin)

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:

  build:
    name: PR integration tests
    runs-on: macos-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Make and install Skaffold binary from current PR
      run: |
        make
        sudo install "${HOME}/work/skaffold/skaffold/out/skaffold" /usr/local/bin/skaffold

    - name: Run integration tests
      run: |
         make quicktest
